//! Vault and oplog routes. Bodies on the ops lanes are postcard-encoded
//! `onyx-proto` messages (binary; every ciphertext byte is opaque here).

use std::sync::Arc;

use axum::Json;
use axum::body::Bytes;
use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, StatusCode};
use data_encoding::HEXLOWER;
use serde::{Deserialize, Serialize};

use crate::ServerState;
use crate::auth::authenticate;

type RouteError = (StatusCode, String);

/// Cap pull batches: a fresh device syncing a huge vault pages through.
const PULL_LIMIT: usize = 2_000;

pub async fn health() -> &'static str {
    "ok"
}

fn vault_id_from(path: &str) -> Result<[u8; 16], RouteError> {
    HEXLOWER
        .decode(path.as_bytes())
        .ok()
        .and_then(|bytes| bytes.try_into().ok())
        .ok_or((StatusCode::BAD_REQUEST, "invalid vault id".into()))
}

fn require_member(
    state: &ServerState,
    vault: [u8; 16],
    device: [u8; 16],
) -> Result<(), RouteError> {
    let member = state
        .db
        .is_member(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if member {
        Ok(())
    } else {
        Err((StatusCode::FORBIDDEN, "not a member of this vault".into()))
    }
}

// ---------------------------------------------------------------------------
// POST /v1/vaults — join (creating if needed)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinRequest {
    /// Hex vault id — a random 128-bit value generated by the first device
    /// and shared with others during (encrypted) device pairing. Knowing
    /// it is the capability to join; the payload it guards is ciphertext
    /// either way.
    pub vault_id: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinResponse {
    pub joined: bool,
}

pub async fn join_vault(
    State(state): State<Arc<ServerState>>,
    headers: HeaderMap,
    Json(request): Json<JoinRequest>,
) -> Result<Json<JoinResponse>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&request.vault_id)?;
    state
        .db
        .join_vault(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(Json(JoinResponse { joined: true }))
}

// ---------------------------------------------------------------------------
// POST /v1/vaults/{vault}/ops — push encrypted ops
// ---------------------------------------------------------------------------

pub async fn push_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let push: onyx_proto::PushOps =
        onyx_proto::decode(&body).map_err(|error| (StatusCode::BAD_REQUEST, error.to_string()))?;
    if push.version != onyx_proto::PROTOCOL_VERSION {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("unsupported protocol version {}", push.version),
        ));
    }

    let head_seq = state
        .db
        .append_ops(vault, device, &push.ops)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    // Wake live-push subscribers (no receivers = no-op).
    let _ = state.hub(vault).send(head_seq);

    onyx_proto::encode(&onyx_proto::PushAck { head_seq })
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// GET /v1/vaults/{vault}/ops?since=N — pull ops
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct PullParams {
    #[serde(default)]
    pub since: u64,
}

pub async fn pull_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    Query(params): Query<PullParams>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let (ops, head_seq) = state
        .db
        .ops_since(vault, params.since, PULL_LIMIT)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    onyx_proto::encode(&onyx_proto::OpsBatch {
        version: onyx_proto::PROTOCOL_VERSION,
        ops,
        head_seq,
    })
    .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// Blob lanes: content-addressed encrypted attachments
// ---------------------------------------------------------------------------

/// Reject absurd uploads (self-host default; configurable later).
const MAX_BLOB_BYTES: usize = 512 * 1024 * 1024;

fn valid_blob_hash(hash: &str) -> bool {
    hash.len() == 64 && hash.bytes().all(|byte| byte.is_ascii_hexdigit())
}

pub async fn put_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    if !valid_blob_hash(&hash) {
        return Err((StatusCode::BAD_REQUEST, "invalid blob hash".into()));
    }
    if body.len() > MAX_BLOB_BYTES {
        return Err((StatusCode::PAYLOAD_TOO_LARGE, "blob too large".into()));
    }
    // Content addressing is verifiable without keys: hash(ciphertext).
    let actual = blake3::hash(&body).to_hex().to_string();
    if actual != hash {
        return Err((StatusCode::BAD_REQUEST, "hash mismatch".into()));
    }
    state
        .db
        .put_blob(vault, &hash, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(StatusCode::CREATED)
}

pub async fn head_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    let exists = state
        .db
        .has_blob(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(if exists {
        StatusCode::OK
    } else {
        StatusCode::NOT_FOUND
    })
}

pub async fn get_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    state
        .db
        .get_blob(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown blob".into()))
}

// ---------------------------------------------------------------------------
// Enrollment relay: opaque sealed blobs under short-lived codes. The
// server can neither read nor usefully tamper (the SAS catches it).
// ---------------------------------------------------------------------------

fn valid_enroll_code(code: &str) -> bool {
    code.len() >= 6
        && code.len() <= 32
        && code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
}

pub async fn enroll_create(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    authenticate(&state, &headers)?;
    if !valid_enroll_code(&code) || body.is_empty() || body.len() > 4096 {
        return Err((StatusCode::BAD_REQUEST, "invalid enrollment".into()));
    }
    let created = state
        .db
        .enroll_create(&code, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if created {
        Ok(StatusCode::CREATED)
    } else {
        Err((StatusCode::CONFLICT, "code already in use".into()))
    }
}

pub async fn enroll_request(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    authenticate(&state, &headers)?;
    state
        .db
        .enroll_request(&code)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown enrollment code".into()))
}

pub async fn enroll_respond(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    authenticate(&state, &headers)?;
    if body.is_empty() || body.len() > 4096 {
        return Err((StatusCode::BAD_REQUEST, "invalid response".into()));
    }
    let stored = state
        .db
        .enroll_respond(&code, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if stored {
        Ok(StatusCode::OK)
    } else {
        Err((StatusCode::NOT_FOUND, "unknown or answered code".into()))
    }
}

pub async fn enroll_claim(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    authenticate(&state, &headers)?;
    state
        .db
        .enroll_claim(&code)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "no response yet".into()))
}

// ---------------------------------------------------------------------------
// Single-note shares: encrypted blob + a public viewer. The decryption key
// lives only in the link fragment, so the server is zero-knowledge here too.
// ---------------------------------------------------------------------------

const MAX_SHARE_BYTES: usize = 8 * 1024 * 1024;

fn valid_share_id(id: &str) -> bool {
    (8..=64).contains(&id.len())
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
}

pub async fn put_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    if !valid_share_id(&id) || body.is_empty() || body.len() > MAX_SHARE_BYTES {
        return Err((StatusCode::BAD_REQUEST, "invalid share".into()));
    }
    state
        .db
        .put_share(&id, device, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(StatusCode::CREATED)
}

/// Public: return the raw ciphertext for a share. No auth — the fragment
/// key is the capability, and the server can't read the content anyway.
pub async fn get_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
) -> Result<Vec<u8>, RouteError> {
    state
        .db
        .get_share(&id)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown share".into()))
}

pub async fn delete_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
    headers: HeaderMap,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let deleted = state
        .db
        .delete_share(&id, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if deleted {
        Ok(StatusCode::NO_CONTENT)
    } else {
        Err((StatusCode::NOT_FOUND, "not your share or unknown".into()))
    }
}

/// The public viewer page: fetches the ciphertext, reads the AES-GCM key
/// from the URL fragment, decrypts with WebCrypto, and displays the
/// pre-rendered HTML. All decryption is client-side; the fragment is never
/// sent to any server.
pub async fn share_viewer() -> axum::response::Html<&'static str> {
    axum::response::Html(SHARE_VIEWER_HTML)
}

const SHARE_VIEWER_HTML: &str = r#"<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shared note · Onyx</title>
<style>
  :root { color-scheme: dark light; }
  body { font-family: system-ui, sans-serif; max-width: 46rem; margin: 2rem auto;
         padding: 0 1rem; line-height: 1.65; background: #16161d; color: #e6e6ec; }
  @media (prefers-color-scheme: light) { body { background: #fbfbfd; color: #1d1d26; } }
  pre { background: #00000022; padding: .6rem; border-radius: 6px; overflow-x: auto; }
  code { font-family: ui-monospace, monospace; }
  img { max-width: 100%; }
  table { border-collapse: collapse; } th,td { border: 1px solid #8884; padding: 4px 10px; }
  .onyx-wikilink { color: #8b7ff5; }
  #err { color: #f56b6b; }
  footer { margin-top: 3rem; font-size: 12px; opacity: .6; }
</style></head>
<body>
<div id="content">Decrypting…</div>
<div id="err"></div>
<footer>End-to-end encrypted share · served by your Onyx server, which cannot read it.</footer>
<script type="module">
const id = location.pathname.split('/').pop();
const keyB64 = location.hash.slice(1);
const b64urlToBytes = (s) => {
  s = s.replace(/-/g,'+').replace(/_/g,'/'); while (s.length % 4) s += '=';
  return Uint8Array.from(atob(s), c => c.charCodeAt(0));
};
try {
  if (!keyB64) throw new Error('This link is missing its decryption key.');
  const rawKey = b64urlToBytes(keyB64);
  const resp = await fetch('/v1/shares/' + encodeURIComponent(id));
  if (!resp.ok) throw new Error('Share not found or revoked.');
  const blob = new Uint8Array(await resp.arrayBuffer());
  const nonce = blob.slice(0, 12), ct = blob.slice(12);
  const key = await crypto.subtle.importKey('raw', rawKey, 'AES-GCM', false, ['decrypt']);
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: nonce }, key, ct);
  document.getElementById('content').innerHTML = new TextDecoder().decode(plain);
} catch (e) {
  document.getElementById('content').textContent = '';
  document.getElementById('err').textContent = String(e.message || e);
}
</script>
</body></html>"#;
