//! Vault and oplog routes. Bodies on the ops lanes are postcard-encoded
//! `onyx-proto` messages (binary; every ciphertext byte is opaque here).

use std::sync::Arc;

use axum::Json;
use axum::body::{Body, Bytes};
use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::Response;
use data_encoding::HEXLOWER;
use serde::{Deserialize, Serialize};

use crate::ServerState;
use crate::auth::authenticate;
use crate::db::CHECKPOINT_THRESHOLD;

type RouteError = (StatusCode, String);

/// Cap pull batches: a fresh device syncing a huge vault pages through.
const PULL_LIMIT: usize = 2_000;

pub async fn health() -> &'static str {
    "ok"
}

fn vault_id_from(path: &str) -> Result<[u8; 16], RouteError> {
    HEXLOWER
        .decode(path.as_bytes())
        .ok()
        .and_then(|bytes| bytes.try_into().ok())
        .ok_or((StatusCode::BAD_REQUEST, "invalid vault id".into()))
}

fn require_member(
    state: &ServerState,
    vault: [u8; 16],
    device: [u8; 16],
) -> Result<(), RouteError> {
    let member = state
        .db
        .is_member(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if member {
        Ok(())
    } else {
        Err((StatusCode::FORBIDDEN, "not a member of this vault".into()))
    }
}

// ---------------------------------------------------------------------------
// POST /v1/vaults — join (creating if needed)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinRequest {
    /// Hex vault id — a random 128-bit value generated by the first device
    /// and shared with others during (encrypted) device pairing. Knowing
    /// it is the capability to join; the payload it guards is ciphertext
    /// either way.
    pub vault_id: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinResponse {
    pub joined: bool,
}

pub async fn join_vault(
    State(state): State<Arc<ServerState>>,
    headers: HeaderMap,
    Json(request): Json<JoinRequest>,
) -> Result<Json<JoinResponse>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&request.vault_id)?;
    state
        .db
        .join_vault(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(Json(JoinResponse { joined: true }))
}

// ---------------------------------------------------------------------------
// POST /v1/vaults/{vault}/ops — push encrypted ops
// ---------------------------------------------------------------------------

pub async fn push_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let push: onyx_proto::PushOps =
        onyx_proto::decode(&body).map_err(|error| (StatusCode::BAD_REQUEST, error.to_string()))?;
    if push.version != onyx_proto::PROTOCOL_VERSION {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("unsupported protocol version {}", push.version),
        ));
    }

    let head_seq = state
        .db
        .append_ops(vault, device, &push.ops)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    // Wake live-push subscribers (no receivers = no-op).
    let _ = state.hub(vault).send(head_seq);

    onyx_proto::encode(&onyx_proto::PushAck { head_seq })
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// GET /v1/vaults/{vault}/ops?since=N — pull ops
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct PullParams {
    #[serde(default)]
    pub since: u64,
}

pub async fn pull_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    Query(params): Query<PullParams>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let (ops, head_seq) = state
        .db
        .ops_since(vault, params.since, PULL_LIMIT)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    // Ask the client to checkpoint any doc whose op history has grown long,
    // so the server can prune the backlog. Only meaningful once the client
    // is caught up (further pages carry no new docs to hint about).
    let checkpoint_hints = if head_seq == 0 || params.since + (ops.len() as u64) >= head_seq {
        state
            .db
            .docs_over_threshold(vault, CHECKPOINT_THRESHOLD)
            .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
    } else {
        Vec::new()
    };

    onyx_proto::encode(&onyx_proto::OpsBatch {
        version: onyx_proto::PROTOCOL_VERSION,
        ops,
        head_seq,
        checkpoint_hints,
    })
    .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// Blob lanes: content-addressed encrypted attachments
// ---------------------------------------------------------------------------

/// Reject absurd uploads (self-host default; configurable later).
const MAX_BLOB_BYTES: u64 = 512 * 1024 * 1024;

/// Upper bound on a single chunk body (the client's chunk size plus slack).
const MAX_CHUNK_BYTES: usize = onyx_proto::BLOB_CHUNK_BYTES * 2;

fn valid_blob_hash(hash: &str) -> bool {
    hash.len() == 64 && hash.bytes().all(|byte| byte.is_ascii_hexdigit())
}

/// Single-shot upload for a small blob (≤ one chunk). Larger blobs use the
/// chunked lane so a dropped connection never restarts the whole transfer.
pub async fn put_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    if !valid_blob_hash(&hash) {
        return Err((StatusCode::BAD_REQUEST, "invalid blob hash".into()));
    }
    if body.len() > MAX_CHUNK_BYTES {
        return Err((
            StatusCode::PAYLOAD_TOO_LARGE,
            "use the chunked lane for large blobs".into(),
        ));
    }
    // Content addressing is verifiable without keys: hash(ciphertext).
    if blake3::hash(&body).to_hex().as_str() != hash {
        return Err((StatusCode::BAD_REQUEST, "hash mismatch".into()));
    }
    state
        .db
        .put_blob(vault, &hash, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(StatusCode::CREATED)
}

#[derive(Deserialize)]
pub struct ChunkParams {
    pub total: u32,
    pub size: u64,
}

/// Upload one chunk of a large blob. Idempotent per index, so a client that
/// dropped mid-transfer re-sends only the chunks the server is missing.
/// Returns 201 once the final chunk completes and verifies, 200 otherwise.
pub async fn put_blob_chunk(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash, idx)): Path<(String, String, u32)>,
    Query(params): Query<ChunkParams>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    if !valid_blob_hash(&hash) {
        return Err((StatusCode::BAD_REQUEST, "invalid blob hash".into()));
    }
    if params.total == 0 || idx >= params.total {
        return Err((StatusCode::BAD_REQUEST, "chunk index out of range".into()));
    }
    if params.size > MAX_BLOB_BYTES {
        return Err((StatusCode::PAYLOAD_TOO_LARGE, "blob too large".into()));
    }
    if body.len() > MAX_CHUNK_BYTES {
        return Err((StatusCode::PAYLOAD_TOO_LARGE, "chunk too large".into()));
    }
    state
        .db
        .blob_begin(vault, &hash, params.total, params.size)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    state
        .db
        .blob_put_chunk(vault, &hash, idx, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    match state.db.blob_try_complete(vault, &hash) {
        Ok(true) => Ok(StatusCode::CREATED),
        Ok(false) => Ok(StatusCode::OK),
        // Reassembly hashed to the wrong value: the client uploaded corrupt
        // or mismatched chunks. The partial upload was discarded; ask again.
        Err(crate::db::DbError::HashMismatch) => {
            Err((StatusCode::BAD_REQUEST, "hash mismatch on reassembly".into()))
        }
        Err(error) => Err((StatusCode::INTERNAL_SERVER_ERROR, error.to_string())),
    }
}

/// Resume status: which chunks the server already holds. A client queries
/// this before (re)uploading so it skips finished chunks.
pub async fn blob_status(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    let status = state
        .db
        .blob_status(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "no such upload".into()))?;
    onyx_proto::encode(&status)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

pub async fn head_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Response, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    // Report the size (so a downloader can plan its ranges) only when the
    // blob is complete; a partial blob is treated as absent.
    let size = state
        .db
        .blob_size(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    let builder = Response::builder().header(header::ACCEPT_RANGES, "bytes");
    let response = match size {
        Some(size) => builder
            .status(StatusCode::OK)
            .header(header::CONTENT_LENGTH, size)
            .body(Body::empty()),
        None => builder.status(StatusCode::NOT_FOUND).body(Body::empty()),
    };
    response.map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

/// Parse an HTTP `Range: bytes=start-[end]` header into an inclusive
/// `(start, end)` within `size`. `None` if absent or unsatisfiable.
fn parse_range(headers: &HeaderMap, size: u64) -> Option<(u64, u64)> {
    let spec = headers
        .get(header::RANGE)?
        .to_str()
        .ok()?
        .strip_prefix("bytes=")?;
    let (start_text, end_text) = spec.split_once('-')?;
    let start: u64 = start_text.trim().parse().ok()?;
    let end: u64 = if end_text.trim().is_empty() {
        size.saturating_sub(1)
    } else {
        end_text.trim().parse().ok()?
    };
    if size == 0 || start > end || start >= size {
        return None;
    }
    Some((start, end.min(size - 1)))
}

pub async fn get_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Response, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    let server_error =
        |error: crate::db::DbError| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string());
    let build_error =
        |error: axum::http::Error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string());

    let Some(size) = state.db.blob_size(vault, &hash).map_err(server_error)? else {
        return Err((StatusCode::NOT_FOUND, "unknown blob".into()));
    };

    // Range request → 206 with just the requested window (bounded RAM, and
    // the client's resume lane). A present-but-unsatisfiable range → 416.
    if headers.contains_key(header::RANGE) {
        let Some((start, end)) = parse_range(&headers, size) else {
            return Err((
                StatusCode::RANGE_NOT_SATISFIABLE,
                "unsatisfiable range".into(),
            ));
        };
        let len = end - start + 1;
        let data = state
            .db
            .blob_read_range(vault, &hash, start, len)
            .map_err(server_error)?
            .ok_or((StatusCode::NOT_FOUND, "unknown blob".into()))?;
        return Response::builder()
            .status(StatusCode::PARTIAL_CONTENT)
            .header(header::ACCEPT_RANGES, "bytes")
            .header(header::CONTENT_RANGE, format!("bytes {start}-{end}/{size}"))
            .header(header::CONTENT_LENGTH, data.len())
            .body(Body::from(data))
            .map_err(build_error);
    }

    let data = state
        .db
        .get_blob(vault, &hash)
        .map_err(server_error)?
        .ok_or((StatusCode::NOT_FOUND, "unknown blob".into()))?;
    Response::builder()
        .status(StatusCode::OK)
        .header(header::ACCEPT_RANGES, "bytes")
        .header(header::CONTENT_LENGTH, data.len())
        .body(Body::from(data))
        .map_err(build_error)
}

// ---------------------------------------------------------------------------
// Enrollment relay: opaque sealed blobs under short-lived codes. The
// server can neither read nor usefully tamper (the SAS catches it).
// ---------------------------------------------------------------------------

fn valid_enroll_code(code: &str) -> bool {
    code.len() >= 6
        && code.len() <= 32
        && code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
}

pub async fn enroll_create(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    authenticate(&state, &headers)?;
    if !valid_enroll_code(&code) || body.is_empty() || body.len() > 4096 {
        return Err((StatusCode::BAD_REQUEST, "invalid enrollment".into()));
    }
    let created = state
        .db
        .enroll_create(&code, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if created {
        Ok(StatusCode::CREATED)
    } else {
        Err((StatusCode::CONFLICT, "code already in use".into()))
    }
}

pub async fn enroll_request(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    authenticate(&state, &headers)?;
    state
        .db
        .enroll_request(&code)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown enrollment code".into()))
}

pub async fn enroll_respond(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    authenticate(&state, &headers)?;
    if body.is_empty() || body.len() > 4096 {
        return Err((StatusCode::BAD_REQUEST, "invalid response".into()));
    }
    let stored = state
        .db
        .enroll_respond(&code, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if stored {
        Ok(StatusCode::OK)
    } else {
        Err((StatusCode::NOT_FOUND, "unknown or answered code".into()))
    }
}

pub async fn enroll_claim(
    State(state): State<Arc<ServerState>>,
    Path(code): Path<String>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    authenticate(&state, &headers)?;
    state
        .db
        .enroll_claim(&code)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "no response yet".into()))
}

// ---------------------------------------------------------------------------
// Single-note shares: encrypted blob + a public viewer. The decryption key
// lives only in the link fragment, so the server is zero-knowledge here too.
// ---------------------------------------------------------------------------

const MAX_SHARE_BYTES: usize = 8 * 1024 * 1024;

fn valid_share_id(id: &str) -> bool {
    (8..=64).contains(&id.len())
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
}

pub async fn put_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    if !valid_share_id(&id) || body.is_empty() || body.len() > MAX_SHARE_BYTES {
        return Err((StatusCode::BAD_REQUEST, "invalid share".into()));
    }
    state
        .db
        .put_share(&id, device, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(StatusCode::CREATED)
}

/// Public: return the raw ciphertext for a share. No auth — the fragment
/// key is the capability, and the server can't read the content anyway.
pub async fn get_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
) -> Result<Vec<u8>, RouteError> {
    state
        .db
        .get_share(&id)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown share".into()))
}

pub async fn delete_share(
    State(state): State<Arc<ServerState>>,
    Path(id): Path<String>,
    headers: HeaderMap,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let deleted = state
        .db
        .delete_share(&id, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if deleted {
        Ok(StatusCode::NO_CONTENT)
    } else {
        Err((StatusCode::NOT_FOUND, "not your share or unknown".into()))
    }
}

/// The public viewer page: fetches the ciphertext, reads the AES-GCM key
/// from the URL fragment, decrypts with WebCrypto, and displays the
/// pre-rendered HTML. All decryption is client-side; the fragment is never
/// sent to any server.
pub async fn share_viewer() -> axum::response::Html<&'static str> {
    axum::response::Html(SHARE_VIEWER_HTML)
}

const SHARE_VIEWER_HTML: &str = r#"<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shared note · Onyx</title>
<style>
  :root { color-scheme: dark light; }
  body { font-family: system-ui, sans-serif; max-width: 46rem; margin: 2rem auto;
         padding: 0 1rem; line-height: 1.65; background: #16161d; color: #e6e6ec; }
  @media (prefers-color-scheme: light) { body { background: #fbfbfd; color: #1d1d26; } }
  pre { background: #00000022; padding: .6rem; border-radius: 6px; overflow-x: auto; }
  code { font-family: ui-monospace, monospace; }
  img { max-width: 100%; }
  table { border-collapse: collapse; } th,td { border: 1px solid #8884; padding: 4px 10px; }
  .onyx-wikilink { color: #8b7ff5; }
  #err { color: #f56b6b; }
  footer { margin-top: 3rem; font-size: 12px; opacity: .6; }
</style></head>
<body>
<div id="content">Decrypting…</div>
<div id="err"></div>
<footer>End-to-end encrypted share · served by your Onyx server, which cannot read it.</footer>
<script type="module">
const id = location.pathname.split('/').pop();
const keyB64 = location.hash.slice(1);
const b64urlToBytes = (s) => {
  s = s.replace(/-/g,'+').replace(/_/g,'/'); while (s.length % 4) s += '=';
  return Uint8Array.from(atob(s), c => c.charCodeAt(0));
};
try {
  if (!keyB64) throw new Error('This link is missing its decryption key.');
  const rawKey = b64urlToBytes(keyB64);
  const resp = await fetch('/v1/shares/' + encodeURIComponent(id));
  if (!resp.ok) throw new Error('Share not found or revoked.');
  const blob = new Uint8Array(await resp.arrayBuffer());
  const nonce = blob.slice(0, 12), ct = blob.slice(12);
  const key = await crypto.subtle.importKey('raw', rawKey, 'AES-GCM', false, ['decrypt']);
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: nonce }, key, ct);
  document.getElementById('content').innerHTML = new TextDecoder().decode(plain);
} catch (e) {
  document.getElementById('content').textContent = '';
  document.getElementById('err').textContent = String(e.message || e);
}
</script>
</body></html>"#;
