//! Vault and oplog routes. Bodies on the ops lanes are postcard-encoded
//! `onyx-proto` messages (binary; every ciphertext byte is opaque here).

use std::sync::Arc;

use axum::Json;
use axum::body::Bytes;
use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, StatusCode};
use data_encoding::HEXLOWER;
use serde::{Deserialize, Serialize};

use crate::ServerState;
use crate::auth::authenticate;

type RouteError = (StatusCode, String);

/// Cap pull batches: a fresh device syncing a huge vault pages through.
const PULL_LIMIT: usize = 2_000;

pub async fn health() -> &'static str {
    "ok"
}

fn vault_id_from(path: &str) -> Result<[u8; 16], RouteError> {
    HEXLOWER
        .decode(path.as_bytes())
        .ok()
        .and_then(|bytes| bytes.try_into().ok())
        .ok_or((StatusCode::BAD_REQUEST, "invalid vault id".into()))
}

fn require_member(
    state: &ServerState,
    vault: [u8; 16],
    device: [u8; 16],
) -> Result<(), RouteError> {
    let member = state
        .db
        .is_member(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    if member {
        Ok(())
    } else {
        Err((StatusCode::FORBIDDEN, "not a member of this vault".into()))
    }
}

// ---------------------------------------------------------------------------
// POST /v1/vaults — join (creating if needed)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinRequest {
    /// Hex vault id — a random 128-bit value generated by the first device
    /// and shared with others during (encrypted) device pairing. Knowing
    /// it is the capability to join; the payload it guards is ciphertext
    /// either way.
    pub vault_id: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinResponse {
    pub joined: bool,
}

pub async fn join_vault(
    State(state): State<Arc<ServerState>>,
    headers: HeaderMap,
    Json(request): Json<JoinRequest>,
) -> Result<Json<JoinResponse>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&request.vault_id)?;
    state
        .db
        .join_vault(vault, device)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(Json(JoinResponse { joined: true }))
}

// ---------------------------------------------------------------------------
// POST /v1/vaults/{vault}/ops — push encrypted ops
// ---------------------------------------------------------------------------

pub async fn push_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let push: onyx_proto::PushOps =
        onyx_proto::decode(&body).map_err(|error| (StatusCode::BAD_REQUEST, error.to_string()))?;
    if push.version != onyx_proto::PROTOCOL_VERSION {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("unsupported protocol version {}", push.version),
        ));
    }

    let head_seq = state
        .db
        .append_ops(vault, device, &push.ops)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    // Wake live-push subscribers (no receivers = no-op).
    let _ = state.hub(vault).send(head_seq);

    onyx_proto::encode(&onyx_proto::PushAck { head_seq })
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// GET /v1/vaults/{vault}/ops?since=N — pull ops
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct PullParams {
    #[serde(default)]
    pub since: u64,
}

pub async fn pull_ops(
    State(state): State<Arc<ServerState>>,
    Path(vault): Path<String>,
    Query(params): Query<PullParams>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;

    let (ops, head_seq) = state
        .db
        .ops_since(vault, params.since, PULL_LIMIT)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;

    onyx_proto::encode(&onyx_proto::OpsBatch {
        version: onyx_proto::PROTOCOL_VERSION,
        ops,
        head_seq,
    })
    .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))
}

// ---------------------------------------------------------------------------
// Blob lanes: content-addressed encrypted attachments
// ---------------------------------------------------------------------------

/// Reject absurd uploads (self-host default; configurable later).
const MAX_BLOB_BYTES: usize = 512 * 1024 * 1024;

fn valid_blob_hash(hash: &str) -> bool {
    hash.len() == 64 && hash.bytes().all(|byte| byte.is_ascii_hexdigit())
}

pub async fn put_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    if !valid_blob_hash(&hash) {
        return Err((StatusCode::BAD_REQUEST, "invalid blob hash".into()));
    }
    if body.len() > MAX_BLOB_BYTES {
        return Err((StatusCode::PAYLOAD_TOO_LARGE, "blob too large".into()));
    }
    // Content addressing is verifiable without keys: hash(ciphertext).
    let actual = blake3::hash(&body).to_hex().to_string();
    if actual != hash {
        return Err((StatusCode::BAD_REQUEST, "hash mismatch".into()));
    }
    state
        .db
        .put_blob(vault, &hash, &body)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(StatusCode::CREATED)
}

pub async fn head_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<StatusCode, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    let exists = state
        .db
        .has_blob(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?;
    Ok(if exists {
        StatusCode::OK
    } else {
        StatusCode::NOT_FOUND
    })
}

pub async fn get_blob(
    State(state): State<Arc<ServerState>>,
    Path((vault, hash)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Vec<u8>, RouteError> {
    let device = authenticate(&state, &headers)?;
    let vault = vault_id_from(&vault)?;
    require_member(&state, vault, device)?;
    state
        .db
        .get_blob(vault, &hash)
        .map_err(|error| (StatusCode::INTERNAL_SERVER_ERROR, error.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "unknown blob".into()))
}
